-- The athlete Overview board: which tiles show and in what order. An array of
-- tile ids (progress.overviewTiles); empty means "the default board". Athlete
-- owned, so it lives on progress like racing stats never did — this one syncs,
-- because a board someone curated should follow them to their next phone.
--
-- merge_progress is re-created WHOLE rather than patched, because the column
-- has to appear in three places and missing the UPDATE set list is the
-- documented failure: the field would sync once on insert and then silently
-- never update again. This file is generated by transforming
-- 20260814120000_stat_field.sql so no other line can drift.
alter table public.progress add column if not exists overview_tiles jsonb not null default '[]'::jsonb;


alter table public.athletes add column if not exists rev bigint not null default 1;
alter table public.progress add column if not exists rev bigint not null default 1;
alter table public.progress add column if not exists day_notes jsonb not null default '{}'::jsonb;

create or replace function public.bump_athletes_rev() returns trigger
language plpgsql as $$
begin
  new.rev := coalesce(old.rev, 0) + 1;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists trg_athletes_rev on public.athletes;
create trigger trg_athletes_rev before update on public.athletes
  for each row execute function public.bump_athletes_rev();

create or replace function public.bump_progress_rev() returns trigger
language plpgsql as $$
begin
  new.rev := coalesce(old.rev, 0) + 1;
  return new;
end $$;
drop trigger if exists trg_progress_rev on public.progress;
create trigger trg_progress_rev before update on public.progress
  for each row execute function public.bump_progress_rev();

-- The merge. security invoker: RLS decides who may touch which row, exactly
-- as it does for the plain upsert this replaces.
create or replace function public.merge_progress(p_athlete_id text, p_payload jsonb)
returns jsonb
language plpgsql
security invoker
as $$
declare
  cur public.progress%rowtype;
  merged_logs jsonb;
  new_rev bigint;
begin
  select * into cur from public.progress where athlete_id = p_athlete_id for update;

  if not found then
    insert into public.progress (
      athlete_id, exercise_logs, bodyweight_log, day_completions,
      personal_records, package_requests, cardio_logs, feedback,
      dismissed_bulletins, seen_messages, total_workout_ms, workout_moods,
      readiness, added_exercises, athlete_days, form_checks, swaps,
      nutrition_targets, food_log, custom_foods, saved_meals, water_log,
      nutrition_game, hoard, avatar_id, day_notes, pending_deloads, stat_field,
      overview_tiles, synced_at
    ) values (
      p_athlete_id,
      coalesce(p_payload->'exercise_logs', '{}'::jsonb),
      coalesce(p_payload->'bodyweight_log', '[]'::jsonb),
      coalesce(p_payload->'day_completions', '{}'::jsonb),
      coalesce(p_payload->'personal_records', '[]'::jsonb),
      coalesce(p_payload->'package_requests', '[]'::jsonb),
      coalesce(p_payload->'cardio_logs', '[]'::jsonb),
      coalesce(p_payload->>'feedback', ''),
      coalesce(p_payload->'dismissed_bulletins', '{}'::jsonb),
      coalesce(p_payload->'seen_messages', '{}'::jsonb),
      coalesce((p_payload->>'total_workout_ms')::bigint, 0),
      coalesce(p_payload->'workout_moods', '{}'::jsonb),
      coalesce(p_payload->'readiness', '{}'::jsonb),
      coalesce(p_payload->'added_exercises', '{}'::jsonb),
      coalesce(p_payload->'athlete_days', '[]'::jsonb),
      coalesce(p_payload->'form_checks', '{}'::jsonb),
      coalesce(p_payload->'swaps', '{}'::jsonb),
      coalesce(p_payload->'nutrition_targets', '{}'::jsonb),
      coalesce(p_payload->'food_log', '{}'::jsonb),
      coalesce(p_payload->'custom_foods', '[]'::jsonb),
      coalesce(p_payload->'saved_meals', '[]'::jsonb),
      coalesce(p_payload->'water_log', '{}'::jsonb),
      coalesce(p_payload->'nutrition_game', '{}'::jsonb),
      coalesce(p_payload->'hoard', '{}'::jsonb),
      nullif(p_payload->>'avatar_id', ''),
      coalesce(p_payload->'day_notes', '{}'::jsonb),
      coalesce(p_payload->'pending_deloads', '{}'::jsonb),
      coalesce(p_payload->'stat_field', '{}'::jsonb),
      coalesce(p_payload->'overview_tiles', '[]'::jsonb),
      now()
    );
    return jsonb_build_object('rev', 1,
      'exercise_logs', coalesce(p_payload->'exercise_logs', '{}'::jsonb));
  end if;

  -- Entry-level union for exercise_logs. distinct on (exid, ek) with
  -- `order by m desc, pri desc` keeps, per entry key, the highest m — and on
  -- a tie the payload copy (pri 2).
  select coalesce(jsonb_object_agg(exid, entries), '{}'::jsonb) into merged_logs
  from (
    select exid, jsonb_agg(entry) as entries
    from (
      select distinct on (exid, ek) exid, entry
      from (
        select kv.key as exid,
               e.value as entry,
               coalesce(nullif(e.value->>'m', '')::numeric, 0) as m,
               coalesce(e.value->>'id', 'd:' || coalesce(e.value->>'date', '')) as ek,
               src.pri
        from (values (cur.exercise_logs, 1),
                     (coalesce(p_payload->'exercise_logs', '{}'::jsonb), 2)) as src(logs, pri)
             cross join lateral jsonb_each(coalesce(src.logs, '{}'::jsonb)) kv
             cross join lateral jsonb_array_elements(
               case when jsonb_typeof(kv.value) = 'array' then kv.value else '[]'::jsonb end) e
      ) flat
      order by exid, ek, m desc, pri desc
    ) winners
    group by exid
  ) agg;

  update public.progress set
    exercise_logs       = merged_logs,
    bodyweight_log      = coalesce(p_payload->'bodyweight_log', bodyweight_log),
    day_completions     = coalesce(p_payload->'day_completions', day_completions),
    personal_records    = coalesce(p_payload->'personal_records', personal_records),
    package_requests    = coalesce(p_payload->'package_requests', package_requests),
    cardio_logs         = coalesce(p_payload->'cardio_logs', cardio_logs),
    feedback            = coalesce(p_payload->>'feedback', feedback),
    dismissed_bulletins = coalesce(p_payload->'dismissed_bulletins', dismissed_bulletins),
    seen_messages       = coalesce(p_payload->'seen_messages', seen_messages),
    total_workout_ms    = coalesce((p_payload->>'total_workout_ms')::bigint, total_workout_ms),
    workout_moods       = coalesce(p_payload->'workout_moods', workout_moods),
    readiness           = coalesce(p_payload->'readiness', readiness),
    added_exercises     = coalesce(p_payload->'added_exercises', added_exercises),
    athlete_days        = coalesce(p_payload->'athlete_days', athlete_days),
    form_checks         = coalesce(p_payload->'form_checks', form_checks),
    swaps               = coalesce(p_payload->'swaps', swaps),
    nutrition_targets   = coalesce(p_payload->'nutrition_targets', nutrition_targets),
    food_log            = coalesce(p_payload->'food_log', food_log),
    custom_foods        = coalesce(p_payload->'custom_foods', custom_foods),
    saved_meals         = coalesce(p_payload->'saved_meals', saved_meals),
    water_log           = coalesce(p_payload->'water_log', water_log),
    nutrition_game      = coalesce(p_payload->'nutrition_game', nutrition_game),
    hoard               = coalesce(p_payload->'hoard', hoard),
    avatar_id           = coalesce(nullif(p_payload->>'avatar_id', ''), avatar_id),
    day_notes           = coalesce(p_payload->'day_notes', day_notes),
    pending_deloads     = coalesce(p_payload->'pending_deloads', pending_deloads),
    stat_field          = coalesce(p_payload->'stat_field', stat_field),
    overview_tiles      = coalesce(p_payload->'overview_tiles', overview_tiles),
    synced_at           = now()
  where athlete_id = p_athlete_id
  returning rev into new_rev;

  return jsonb_build_object('rev', new_rev, 'exercise_logs', merged_logs);
end $$;

grant execute on function public.merge_progress(text, jsonb) to authenticated;

do $$ begin
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public'
                   and tablename = 'athletes') then
    alter publication supabase_realtime add table public.athletes;
  end if;
  if not exists (select 1 from pg_publication_tables
                 where pubname = 'supabase_realtime' and schemaname = 'public'
                   and tablename = 'progress') then
    alter publication supabase_realtime add table public.progress;
  end if;
end $$;
